/*

 WORLDTILE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 20
   Tile set      : C:\Users\RudeB\Desktop\marioTileSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define windowTileWidth 12
#define windowTileHeight 1
#define windowTileBank 0

unsigned char windowTile[] =
{
  0x1D, 0x0D, 0x19, 0x1C, 0x0F, 0x00, 
  0x00, 0x00, 0x16, 0x13, 0x20, 0x0F
};

/* End of WORLDTILE.C */
